POD-2310: Remove SA from Workspace
broadinstitute/ops-terra-utils pull request #163
Opened 2024-11-25 19:51 UTC by sahakiann

[POD-2310](https://broadinstitute.atlassian.net/browse/POD-2310)

2024-11-25 19:54 UTC, snovod requested changes
I think we only to remove the OLD data_ingest_sa when we are deleting older dataset

2024-11-25 20:00 UTC, John-Scira approved these changes

2024-11-26 17:04 UTC, sahakiann commented on python/set_up_staging_workspace_and_dataset.py
> +    if delete_existing_dataset:
Hm not sure what you mean - the `get_sa_for_dataset_to_delete()` method is being called before the `run()` method. So it removes access for the SA associated with the dataset that's about to get deleted before creating the new dataset.

2024-11-26 17:15 UTC, sahakiann commented on python/set_up_staging_workspace_and_dataset.py
> +            data_project = dataset_to_delete_metadata[0]["dataProject"]
Good point, updated! Forgot that was a method that existed

2024-11-26 17:45 UTC, snovod commented on python/set_up_staging_workspace_and_dataset.py
> +    if delete_existing_dataset:
Sorry, I completyly missed that it is initiliatzed but run isn't called.

2024-11-26 17:45 UTC, snovod approved these changes

2024-11-26 17:53 UTC, merged